services:
  - docker

env:
  global:
    - DOCKER_ORG=koinos
    - DOCKER_REPO=automatic-fogata

jobs:
  include:
    - if: branch = main
      env:
      - TAG=latest
    - if: NOT (branch = main)
      env:
      - TAG=${TRAVIS_BRANCH}

script:
  - docker build . -t ${DOCKER_ORG}/${DOCKER_REPO}:${TAG}

after_sucess:
  - echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin
  - docker push ${DOCKER_ORG}/${DOCKER_REPO}:${TAG}
