services:
  - docker

env:
  global:
    - DOCKER_ORG=koinos
    - DOCKER_REPO=automatic-fogata

before_script:
  - export TAG=`if [ "${TRAVIS_BRANCH}" = "main" ]; then; echo -n latest; else; echo -n ${TRAVIS_BRANCH}; fi;`

script:
  - docker build . -t ${DOCKER_ORG}/${DOCKER_REPO}:${TAG}

after_sucess:
  - echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin
  - docker push ${DOCKER_ORG}/${DOCKER_REPO}:${TAG}
