services:
  - docker

env:
  global:
    - SH=bash
    - DOCKER_ORG=koinos
    - DOCKER_REPO=automatic-fogata

before_script:
  - if [[ $TRAVIS_BRANCH == "main "]]; then
      export TAG=latest
    else
      export TAG=$TRAVIS_BRANCH
    fi

script:
  - docker build . -t ${DOCKER_ORG}/${DOCKER_REPO}:${TAG}

after_sucess:
  - echo "${DOCKER_PASSWORD}" | docker login -u ${DOCKER_USERNAME} --password-stdin
  - docker push ${DOCKER_ORG}/${DOCKER_REPO}:${TAG}
